version: "3.8"
services:
  web:
    image: falcon_mysql_test
    build: .
    volumes:
      - .:/app
    command: gunicorn -c settings.py composites.chat_api:app
    expose:
      - "8888"
    ports:
      - 8888:8888
    restart: always
    networks:
      - network_falcon_test
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: "bootcamp"
      MYSQL_USER: "exchange"
      MYSQL_PASSWORD: "exchange"
      MYSQL_ROOT_PASSWORD: "exchange"
      MYSQL_TCP_PORT: 3307
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - network_falcon_test
networks:
  network_falcon_test: {}