version: "3.7"
services:
  web:
    build: .
    command: python /usr/src/SeaWar/manage.py runserver 0.0.0.0:8000
#    command: bash -c "python /usr/src/SeaWar/manage.py runserver migrate &&
#              python /usr/src/SeaWar/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/SeaWar
      - /home/alameda/PycharmProjects/BattleShips/logs/debug.log:/usr/src/logs/debug.log
    expose:
      - "8000"
    ports:
      - 8000:8000
    restart: always
    links:
      - db
      - redis_db
    depends_on:
      - db
      - redis_db
  db:
    image: mysql:5.7
    expose:
      - "3308"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "SeaWar"
      MYSQL_USER: "alameda"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  redis_db:
    image: redis
    ports:
      - 6380:6379
  nginx:
    image: nginx:1.21.1-alpine
    container_name: nginx
    tty: true
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_params:/etc/nginx/proxy_params
      - ./frontend/:/usr/src/SeaWar/frontend/
    links:
      - web
    ports:
      - 8989:8989